### PR TITLE
New api 4.0.1

### LINKED ISSUE #4: Configurable keyboard shortcut for adding new pages to the list
It would be nice to have a configurable keyboard shortcut for adding new pages to the read later list.

### LINKED ISSUE #13: Allow exporting and importing URLs from JSON format for safety.
This should help users to export the data saved in the storage as a raw file. Should be super easy by just doing `storage.get` and then download the content as json file.

### LINKED ISSUE #15: Deprecate the count key in storage
Deprecate the count key in storage, as the count values need to be computed on the fly because of the possible access of storage of background and popup.

Make sure the older data is not corrupted. Make things migrate smoothly by checking for existing count keys and then cleaning up the key from the storage object.

### LINKED ISSUE #16: Shift all the core code into a common file core.js
Shift all the core code into a common file `core.js`, only the front end codes should be in `popup.js` and all the background codes should be in `background.js`

### LINKED ISSUE #17: Add Linting profile
Add ESLint profile to the code as suggested by @kav2k

### LINKED ISSUE #19: Add title text for links in the popup list.
These should let the user know the full title of the URL as well as the date time when it was added.

### LINKED ISSUE #20: Add headers to each file
Add headers to each of the code files. Should remove `Last Modified` and `Version` info from it.

### PR DESCRIPTION
**Pull request by napsternxg**
This change uses the new API which has the backend and frontend code
separate. The code is now in three parts:
- core.js: has all the basic api code.
- background.js: uses API to create a background app.
- popup.js: uses API to create frontend app.
- All changes happen by using a call back to the storage sync functions.
- Fixes #15 and Fixes #16 

Other changes:
- Keyboard shortcut is Ctrl + Shift + L. Fixes #4 
- Updated manifest. Fixes #8 
- package.json added 
- Linter profile added. Fixes #17  

Fixes #4, #11, #14, #15, #16

- Better way to get filtered list of items for UI. Fixes #16
- Add title to list items. Fixes #19
- Add some license details and headers to each of the files. Fixes #20
- Allow download as JSON. Fixes #13
- Make the title smaller on the popup. Saves space.
- Updated manifest.json
- Removed useless files.
- Cleaned up code using linter.
- Updated README

### CODE REVIEW

**Comment by kav2k** [comment]
I'm sorry, but _have you tested it yourself_?

You pushed out a broken update, 4.0.1 is nonfunctional.

I said I'd test it if I have time, but I haven't claimed I did by now:

> the code is (presumably) working now
> I'll do a testing run. If able, that is - I'll be quite busy until the end of next week.

**Comment by kav2k** [comment]
My apologies; I overreacted to this issue (due to misinterpreting what the error was).

4.0.1 was functional, but old data (`"count"`) was causing trouble. It wouldn't be trivial to catch in testing.

**Comment by napsternxg** [comment]
No worries. The current version is 4.0.3 and works on my machine which has count, mix of old links without timestamp and new links with timestamp. In future, I wish to include a function which does some cleaning of the storage on the update of the API and removes these inconsistencies. That would require some work so I will leave of for later.

**Comment by kav2k** [comment]
I would recommend keeping the storage schema version in the storage, that removes the need for heuristics when you change the data format.

**Pull request merged**
